---
- name: Update all packages
  dnf:
    name: "*"
    state: latest
    update_only: true
    exclude: curl

- name: Install common utilities
  dnf:
    name:
      - wget
      - unzip
      - git
      - tar
    state: present
